all:
  children:
    linux_servers:
      hosts:
        linux-web-01:
          ansible_host: 192.168.1.10
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        linux-db-01:
          ansible_host: 192.168.1.11
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_become: yes
        ansible_become_method: sudo
    
    windows_servers:
      hosts:
        win-web-01:
          ansible_host: 192.168.1.20
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password }}"
        win-app-01:
          ansible_host: 192.168.1.21
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password }}"
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: kerberos
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985
    
    development:
      children:
        - linux_servers
        - windows_servers
      vars:
        environment: dev
    
    production:
      children:
        - linux_servers
        - windows_servers
      vars:
        environment: prod
